{
 "title": "ESP32 - BME280 - MQ2 - PMS7003",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(system_chip_model,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pressure{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Quality - Gases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "{instance=\"$instance\", sensor=\"MQ-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Quality - PM 1 / 2,5 / 10",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "PM_2_5_Env{instance=\"$instance\", sensor=\"PMS7003\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PM_1_Env{instance=\"$instance\", sensor=\"PMS7003\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PM_10_0_Env{instance=\"$instance\", sensor=\"PMS7003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chip Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_chip_model{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_core_version{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nbr of Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_chip_cores{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mac Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_mac_address{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESP32 Ip",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_local_ip{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDK Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_sdk_version{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chip Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_flash_chip_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sketch Size Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_sketch_size{instance=~\"$instance\"} * 100) / (system_sketch_size{instance=~\"$instance\"} +system_free_sketch_space{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESP32 Up Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(system_uptime_total{instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength RSSI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "wifi_rssi{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Available Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "system_free_heap{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "{instance=~\"$instance\"} |= ``"
    }
   ]
  }
 ]
}